[package]
name = "dino-cave"
version = "0.1.0"
authors = ["Florian Merz <fmerz@mozilla.com>"]

[dependencies]
actix-web = "0.6.15"
serde_json = "1.0.24"
base64 = "0.9.2"
serde_derive = "1.0.70"
chashmap = "2.2.0"

[dependencies.serde]
version = "1.0.70"
features = ["rc"]